/* Generated By:JavaCC: Do not edit this line. RSPQLParserConstants.java */
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.rspql.lang.rspql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RSPQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int WS = 8;
  /** RegularExpression Id. */
  int WSC = 9;
  /** RegularExpression Id. */
  int IRIref = 10;
  /** RegularExpression Id. */
  int PNAME_NS = 11;
  /** RegularExpression Id. */
  int PNAME_LN = 12;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 13;
  /** RegularExpression Id. */
  int VAR1 = 14;
  /** RegularExpression Id. */
  int VAR2 = 15;
  /** RegularExpression Id. */
  int LANGTAG = 16;
  /** RegularExpression Id. */
  int A2Z = 17;
  /** RegularExpression Id. */
  int A2ZN = 18;
  /** RegularExpression Id. */
  int KW_A = 19;
  /** RegularExpression Id. */
  int BASE = 20;
  /** RegularExpression Id. */
  int PREFIX = 21;
  /** RegularExpression Id. */
  int SELECT = 22;
  /** RegularExpression Id. */
  int DISTINCT = 23;
  /** RegularExpression Id. */
  int REDUCED = 24;
  /** RegularExpression Id. */
  int DESCRIBE = 25;
  /** RegularExpression Id. */
  int CONSTRUCT = 26;
  /** RegularExpression Id. */
  int ASK = 27;
  /** RegularExpression Id. */
  int LIMIT = 28;
  /** RegularExpression Id. */
  int OFFSET = 29;
  /** RegularExpression Id. */
  int ORDER = 30;
  /** RegularExpression Id. */
  int BY = 31;
  /** RegularExpression Id. */
  int VALUES = 32;
  /** RegularExpression Id. */
  int UNDEF = 33;
  /** RegularExpression Id. */
  int ASC = 34;
  /** RegularExpression Id. */
  int DESC = 35;
  /** RegularExpression Id. */
  int NAMED = 36;
  /** RegularExpression Id. */
  int FROM = 37;
  /** RegularExpression Id. */
  int REGISTER = 38;
  /** RegularExpression Id. */
  int WINDOW = 39;
  /** RegularExpression Id. */
  int ON = 40;
  /** RegularExpression Id. */
  int RANGE = 41;
  /** RegularExpression Id. */
  int ITEM = 42;
  /** RegularExpression Id. */
  int STEP = 43;
  /** RegularExpression Id. */
  int TIME = 44;
  /** RegularExpression Id. */
  int PASTNOW = 45;
  /** RegularExpression Id. */
  int RSTREAM = 46;
  /** RegularExpression Id. */
  int ISTREAM = 47;
  /** RegularExpression Id. */
  int DSTREAM = 48;
  /** RegularExpression Id. */
  int WHERE = 49;
  /** RegularExpression Id. */
  int AND = 50;
  /** RegularExpression Id. */
  int GRAPH = 51;
  /** RegularExpression Id. */
  int OPTIONAL = 52;
  /** RegularExpression Id. */
  int UNION = 53;
  /** RegularExpression Id. */
  int MINUS_P = 54;
  /** RegularExpression Id. */
  int BIND = 55;
  /** RegularExpression Id. */
  int SERVICE = 56;
  /** RegularExpression Id. */
  int LET = 57;
  /** RegularExpression Id. */
  int EXISTS = 58;
  /** RegularExpression Id. */
  int NOT = 59;
  /** RegularExpression Id. */
  int AS = 60;
  /** RegularExpression Id. */
  int GROUP = 61;
  /** RegularExpression Id. */
  int HAVING = 62;
  /** RegularExpression Id. */
  int SEPARATOR = 63;
  /** RegularExpression Id. */
  int AGG = 64;
  /** RegularExpression Id. */
  int COUNT = 65;
  /** RegularExpression Id. */
  int MIN = 66;
  /** RegularExpression Id. */
  int MAX = 67;
  /** RegularExpression Id. */
  int SUM = 68;
  /** RegularExpression Id. */
  int AVG = 69;
  /** RegularExpression Id. */
  int STDDEV = 70;
  /** RegularExpression Id. */
  int SAMPLE = 71;
  /** RegularExpression Id. */
  int GROUP_CONCAT = 72;
  /** RegularExpression Id. */
  int FILTER = 73;
  /** RegularExpression Id. */
  int BOUND = 74;
  /** RegularExpression Id. */
  int COALESCE = 75;
  /** RegularExpression Id. */
  int IN = 76;
  /** RegularExpression Id. */
  int IF = 77;
  /** RegularExpression Id. */
  int BNODE = 78;
  /** RegularExpression Id. */
  int IRI = 79;
  /** RegularExpression Id. */
  int URI = 80;
  /** RegularExpression Id. */
  int CAST = 81;
  /** RegularExpression Id. */
  int CALL = 82;
  /** RegularExpression Id. */
  int MULTI = 83;
  /** RegularExpression Id. */
  int SHORTEST = 84;
  /** RegularExpression Id. */
  int STR = 85;
  /** RegularExpression Id. */
  int STRLANG = 86;
  /** RegularExpression Id. */
  int STRDT = 87;
  /** RegularExpression Id. */
  int DTYPE = 88;
  /** RegularExpression Id. */
  int LANG = 89;
  /** RegularExpression Id. */
  int LANGMATCHES = 90;
  /** RegularExpression Id. */
  int IS_URI = 91;
  /** RegularExpression Id. */
  int IS_IRI = 92;
  /** RegularExpression Id. */
  int IS_BLANK = 93;
  /** RegularExpression Id. */
  int IS_LITERAL = 94;
  /** RegularExpression Id. */
  int IS_NUMERIC = 95;
  /** RegularExpression Id. */
  int REGEX = 96;
  /** RegularExpression Id. */
  int SAME_TERM = 97;
  /** RegularExpression Id. */
  int RAND = 98;
  /** RegularExpression Id. */
  int ABS = 99;
  /** RegularExpression Id. */
  int CEIL = 100;
  /** RegularExpression Id. */
  int FLOOR = 101;
  /** RegularExpression Id. */
  int ROUND = 102;
  /** RegularExpression Id. */
  int CONCAT = 103;
  /** RegularExpression Id. */
  int SUBSTR = 104;
  /** RegularExpression Id. */
  int STRLEN = 105;
  /** RegularExpression Id. */
  int REPLACE = 106;
  /** RegularExpression Id. */
  int UCASE = 107;
  /** RegularExpression Id. */
  int LCASE = 108;
  /** RegularExpression Id. */
  int ENCODE_FOR_URI = 109;
  /** RegularExpression Id. */
  int CONTAINS = 110;
  /** RegularExpression Id. */
  int STRSTARTS = 111;
  /** RegularExpression Id. */
  int STRENDS = 112;
  /** RegularExpression Id. */
  int STRBEFORE = 113;
  /** RegularExpression Id. */
  int STRAFTER = 114;
  /** RegularExpression Id. */
  int YEAR = 115;
  /** RegularExpression Id. */
  int MONTH = 116;
  /** RegularExpression Id. */
  int DAY = 117;
  /** RegularExpression Id. */
  int HOURS = 118;
  /** RegularExpression Id. */
  int MINUTES = 119;
  /** RegularExpression Id. */
  int SECONDS = 120;
  /** RegularExpression Id. */
  int TIMEZONE = 121;
  /** RegularExpression Id. */
  int TZ = 122;
  /** RegularExpression Id. */
  int NOW = 123;
  /** RegularExpression Id. */
  int UUID = 124;
  /** RegularExpression Id. */
  int STRUUID = 125;
  /** RegularExpression Id. */
  int VERSION = 126;
  /** RegularExpression Id. */
  int MD5 = 127;
  /** RegularExpression Id. */
  int SHA1 = 128;
  /** RegularExpression Id. */
  int SHA224 = 129;
  /** RegularExpression Id. */
  int SHA256 = 130;
  /** RegularExpression Id. */
  int SHA384 = 131;
  /** RegularExpression Id. */
  int SHA512 = 132;
  /** RegularExpression Id. */
  int TRUE = 133;
  /** RegularExpression Id. */
  int FALSE = 134;
  /** RegularExpression Id. */
  int DATA = 135;
  /** RegularExpression Id. */
  int INSERT = 136;
  /** RegularExpression Id. */
  int DELETE = 137;
  /** RegularExpression Id. */
  int INSERT_DATA = 138;
  /** RegularExpression Id. */
  int DELETE_DATA = 139;
  /** RegularExpression Id. */
  int DELETE_WHERE = 140;
  /** RegularExpression Id. */
  int LOAD = 141;
  /** RegularExpression Id. */
  int CLEAR = 142;
  /** RegularExpression Id. */
  int CREATE = 143;
  /** RegularExpression Id. */
  int ADD = 144;
  /** RegularExpression Id. */
  int MOVE = 145;
  /** RegularExpression Id. */
  int COPY = 146;
  /** RegularExpression Id. */
  int META = 147;
  /** RegularExpression Id. */
  int SILENT = 148;
  /** RegularExpression Id. */
  int DROP = 149;
  /** RegularExpression Id. */
  int INTO = 150;
  /** RegularExpression Id. */
  int TO = 151;
  /** RegularExpression Id. */
  int DFT = 152;
  /** RegularExpression Id. */
  int ALL = 153;
  /** RegularExpression Id. */
  int WITH = 154;
  /** RegularExpression Id. */
  int USING = 155;
  /** RegularExpression Id. */
  int DIGITS = 156;
  /** RegularExpression Id. */
  int INTEGER = 157;
  /** RegularExpression Id. */
  int DECIMAL = 158;
  /** RegularExpression Id. */
  int DOUBLE = 159;
  /** RegularExpression Id. */
  int INTEGER_POSITIVE = 160;
  /** RegularExpression Id. */
  int DECIMAL_POSITIVE = 161;
  /** RegularExpression Id. */
  int DOUBLE_POSITIVE = 162;
  /** RegularExpression Id. */
  int INTEGER_NEGATIVE = 163;
  /** RegularExpression Id. */
  int DECIMAL_NEGATIVE = 164;
  /** RegularExpression Id. */
  int DOUBLE_NEGATIVE = 165;
  /** RegularExpression Id. */
  int EXPONENT = 166;
  /** RegularExpression Id. */
  int QUOTE_3D = 167;
  /** RegularExpression Id. */
  int QUOTE_3S = 168;
  /** RegularExpression Id. */
  int ECHAR = 169;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 170;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 171;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 172;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 173;
  /** RegularExpression Id. */
  int LPAREN = 174;
  /** RegularExpression Id. */
  int RPAREN = 175;
  /** RegularExpression Id. */
  int NIL = 176;
  /** RegularExpression Id. */
  int LBRACE = 177;
  /** RegularExpression Id. */
  int RBRACE = 178;
  /** RegularExpression Id. */
  int LBRACKET = 179;
  /** RegularExpression Id. */
  int RBRACKET = 180;
  /** RegularExpression Id. */
  int ANON = 181;
  /** RegularExpression Id. */
  int SEMICOLON = 182;
  /** RegularExpression Id. */
  int COMMA = 183;
  /** RegularExpression Id. */
  int DOT = 184;
  /** RegularExpression Id. */
  int EQ = 185;
  /** RegularExpression Id. */
  int NE = 186;
  /** RegularExpression Id. */
  int GT = 187;
  /** RegularExpression Id. */
  int LT = 188;
  /** RegularExpression Id. */
  int LE = 189;
  /** RegularExpression Id. */
  int GE = 190;
  /** RegularExpression Id. */
  int BANG = 191;
  /** RegularExpression Id. */
  int TILDE = 192;
  /** RegularExpression Id. */
  int COLON = 193;
  /** RegularExpression Id. */
  int SC_OR = 194;
  /** RegularExpression Id. */
  int SC_AND = 195;
  /** RegularExpression Id. */
  int PLUS = 196;
  /** RegularExpression Id. */
  int MINUS = 197;
  /** RegularExpression Id. */
  int STAR = 198;
  /** RegularExpression Id. */
  int SLASH = 199;
  /** RegularExpression Id. */
  int DATATYPE = 200;
  /** RegularExpression Id. */
  int AT = 201;
  /** RegularExpression Id. */
  int ASSIGN = 202;
  /** RegularExpression Id. */
  int VBAR = 203;
  /** RegularExpression Id. */
  int CARAT = 204;
  /** RegularExpression Id. */
  int FPATH = 205;
  /** RegularExpression Id. */
  int RPATH = 206;
  /** RegularExpression Id. */
  int QMARK = 207;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 208;
  /** RegularExpression Id. */
  int PN_CHARS_U = 209;
  /** RegularExpression Id. */
  int PN_CHARS = 210;
  /** RegularExpression Id. */
  int PN_PREFIX = 211;
  /** RegularExpression Id. */
  int PN_LOCAL = 212;
  /** RegularExpression Id. */
  int VARNAME = 213;
  /** RegularExpression Id. */
  int PN_LOCAL_ESC = 214;
  /** RegularExpression Id. */
  int PLX = 215;
  /** RegularExpression Id. */
  int HEX = 216;
  /** RegularExpression Id. */
  int PERCENT = 217;
  /** RegularExpression Id. */
  int UNKNOWN = 218;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"NOW-\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<WS>",
    "<WSC>",
    "<IRIref>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"base\"",
    "\"prefix\"",
    "\"select\"",
    "\"distinct\"",
    "\"reduced\"",
    "\"describe\"",
    "\"construct\"",
    "\"ask\"",
    "\"limit\"",
    "\"offset\"",
    "\"order\"",
    "\"by\"",
    "\"values\"",
    "\"undef\"",
    "\"asc\"",
    "\"desc\"",
    "\"named\"",
    "\"from\"",
    "\"register stream\"",
    "\"window\"",
    "\"on\"",
    "\"range\"",
    "\"item\"",
    "\"step\"",
    "<TIME>",
    "\"NOW-\"",
    "\"rstream\"",
    "\"istream\"",
    "\"dstream\"",
    "\"where\"",
    "\"and\"",
    "\"graph\"",
    "\"optional\"",
    "\"union\"",
    "\"minus\"",
    "\"bind\"",
    "\"service\"",
    "\"let\"",
    "\"exists\"",
    "\"not\"",
    "\"as\"",
    "\"group\"",
    "\"having\"",
    "\"separator\"",
    "\"agg\"",
    "\"count\"",
    "\"min\"",
    "\"max\"",
    "\"sum\"",
    "\"avg\"",
    "\"stdev\"",
    "\"sample\"",
    "\"group_concat\"",
    "\"filter\"",
    "\"bound\"",
    "\"coalesce\"",
    "\"in\"",
    "\"if\"",
    "\"bnode\"",
    "\"iri\"",
    "\"uri\"",
    "\"cast\"",
    "\"call\"",
    "\"multi\"",
    "\"shortest\"",
    "\"str\"",
    "\"strlang\"",
    "\"strdt\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"isNumeric\"",
    "\"regex\"",
    "\"sameTerm\"",
    "\"RAND\"",
    "\"ABS\"",
    "\"CEIL\"",
    "\"FLOOR\"",
    "\"ROUND\"",
    "\"CONCAT\"",
    "\"SUBSTR\"",
    "\"STRLEN\"",
    "\"REPLACE\"",
    "\"UCASE\"",
    "\"LCASE\"",
    "\"ENCODE_FOR_URI\"",
    "\"CONTAINS\"",
    "\"STRSTARTS\"",
    "\"STRENDS\"",
    "\"STRBEFORE\"",
    "\"STRAFTER\"",
    "\"YEAR\"",
    "\"MONTH\"",
    "\"DAY\"",
    "\"HOURS\"",
    "\"MINUTES\"",
    "\"SECONDS\"",
    "\"TIMEZONE\"",
    "\"TZ\"",
    "\"NOW\"",
    "\"UUID\"",
    "\"STRUUID\"",
    "\"VERSION\"",
    "\"MD5\"",
    "\"SHA1\"",
    "\"SHA224\"",
    "\"SHA256\"",
    "\"SHA384\"",
    "\"SHA512\"",
    "\"true\"",
    "\"false\"",
    "\"data\"",
    "\"insert\"",
    "\"delete\"",
    "<INSERT_DATA>",
    "<DELETE_DATA>",
    "<DELETE_WHERE>",
    "\"load\"",
    "\"clear\"",
    "\"create\"",
    "\"add\"",
    "\"move\"",
    "\"copy\"",
    "\"meta\"",
    "\"silent\"",
    "\"drop\"",
    "\"into\"",
    "\"to\"",
    "\"default\"",
    "\"all\"",
    "\"with\"",
    "\"using\"",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<INTEGER_POSITIVE>",
    "<DECIMAL_POSITIVE>",
    "<DOUBLE_POSITIVE>",
    "<INTEGER_NEGATIVE>",
    "<DECIMAL_NEGATIVE>",
    "<DOUBLE_NEGATIVE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"~\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^^\"",
    "\"@\"",
    "\":=\"",
    "\"|\"",
    "\"^\"",
    "\"->\"",
    "\"<-\"",
    "\"?\"",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<PN_LOCAL_ESC>",
    "<PLX>",
    "<HEX>",
    "<PERCENT>",
    "<UNKNOWN>",
  };

}
